# Generated by Django 4.2 on 2023-04-23 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Auction_auth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="picture",
            field=models.ImageField(
                default="img/user.png", null=True, upload_to="uploads/"
            ),
        ),
    ]
