# Generated by Django 4.2 on 2023-04-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Auction_auth", "0003_furniture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="furniture",
            name="end_date_and_time",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="furniture",
            name="start_date_and_time",
            field=models.DateTimeField(null=True),
        ),
    ]
