# Generated by Django 4.2 on 2023-04-28 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Auction_auth", "0004_alter_furniture_end_date_and_time_and_more"),
    ]

    operations = [
        migrations.DeleteModel(name="Furniture",),
    ]
