# Generated by Django 4.2 on 2023-04-28 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Auction_auth", "0006_furniture"),
    ]

    operations = [
        migrations.AddField(
            model_name="furniture",
            name="is_sold",
            field=models.BooleanField(default=False),
        ),
    ]
