# Generated by Django 4.2 on 2023-04-29 02:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("Auction_auth", "0007_furniture_is_sold"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bidding",
            fields=[
                (
                    "bid_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("bid_price", models.FloatField()),
                (
                    "bid_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="bid_date"),
                ),
                (
                    "bider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "furniture",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Auction_auth.furniture",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Bidding", "db_table": "Bidding",},
        ),
    ]
