# Generated by Django 4.2 on 2024-02-23 12:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("Auction_auth", "0009_furniture_sold_price_furniture_sold_to"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bidding", old_name="furniture", new_name="product",
        ),
        migrations.RenameField(
            model_name="furniture", old_name="furniture_desc", new_name="product_desc",
        ),
        migrations.RenameField(
            model_name="furniture", old_name="furniture_id", new_name="product_id",
        ),
        migrations.RemoveField(model_name="furniture", name="furniture_name",),
        migrations.AddField(
            model_name="furniture",
            name="product_name",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
